create a new function that looks up for exceptions in module tdk-py
this was kinda necessary since it throws error if the result is None: https://github.com/emreozcan/tdk-py/blob/master/src/tdk/gts/__init__.py#L25

This was the error that was thrown when the search resulted with an error on client side.
```console
        *** DISCORD BOT ***
Message from berkantkz#7475: <@966110075901083648> fgudfhdh
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\berka\AppData\Roaming\Python\Python310\site-packages\discord\client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\berka\stuff\tdksozlukbot\tdksozlukbot.py", line 163, in on_message
    arama_sonuclari = tdk.gts.search(query)
  File "C:\Python310\lib\site-packages\tdk\gts\__init__.py", line 25, in search
    raise TdkSearchErrorException(f'{words["error"]} ({query})')
tdk.exceptions.TdkSearchErrorException: TDK GTS Search responded with an error: Sonuç bulunamadı (fgudfhdh)
```